version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "Qwerty123$$%"
      ACCEPT_EULA: "Y"
      MSSQL_DB: "BitsOrch"
      
volumes:
  dbdata:
    driver: local
