#docker-compose up -d
version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Qwerty@123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"


